### PR TITLE
Add some commands and aliases

### PR DESCRIPTION
**Pull request by am11**
```gdb
# Search for commands matching a REGEXP
apropos

# Dump target code/data to a local file.
dump

# Step program, proceeding through subroutine calls.
# (alias of 'next')
n

# Ask an Objective-C object to print itself.
po

# Print value of expression EXP.
# (alias of 'print')
p

# Start debugged program.
# (alias of 'run')
r

# Step program until it reaches a different source line.
# (alias of 'step')
s
```

### CODE REVIEW

**Comment by am11** [comment]
(slightly off-topic) Is it possible to enable the inline comments as well:

```gdb
# catch all <- classified as a comment
catch throw # catch all <- does not get classified as a comment
```

**Comment by am11** [comment]
(slightly off-topic) Is it possible to enable inline comments as well:

```gdb
# catch all <- classified as a comment
catch throw # catch all <- does not get classified as a comment
```

**Comment by am11** [comment]
@pchaigno, could you please take a look? :)

**Comment by pchaigno** [comment]
@am11 I'm not a maintainer.

**Pull request merged**
