### PR TITLE
Add a syntax file for gdbinit files

### PR DESCRIPTION
**Pull request by pope**

### CODE REVIEW

**Comment by pope** [comment]
BTW, not sure how you want the file named, but that's easy enough to change

**Comment by michaelkschmidt** [comment]
@pope Sorry for the long delay.  Do you have an example .gitinit file that we can use to test this?  It would be nice to be able to do a spot check to make sure its working correctly, especially after any future changes.

**Comment by pope** [comment]
Sure. You can check out https://github.com/gdbinit/gdbinit for a fairly complicated gdbinit file. Or are you looking for something that would go in this repo?

One thing of note with that file, the parser does get hung up at line 3109 (just found this as I combed over the file). Looks like my order of operations is off as I should parse the shell subprocess $(...) before the string double quotes. Let me see about fixing that.

**Comment by michaelkschmidt** [comment]
@pope Do you mind creating an "example" folder and putting a gdbinit file in it?  Its cool to use the one you linked.  Eventually we need to do the same for the rest of the .tmLanguage files, too.

I'll go ahead and merge what you have.  Thanks again for all the help

**Pull request merged**
